version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./front_end/build:/var/www/front_end
    depends_on:
      - backend
      - frontend
  mongo_db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - ./mongo/db:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./back_end
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./back_end:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo_db
  frontend:
    build: ./front_end
    volumes:
      - ./front_end:/app
      - '/app/node_modules'
    ports:
      - "3000:3000"
    stdin_open: true